export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOADING = 'LOADING';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const GET_UNREAD_SUCCESS = 'GET_UNREAD_SUCCESS';
export const GET_UNREAD_ERROR = 'GET_UNREAD_ERROR';
export const GET_READ_SUCCESS = 'GET_READ_SUCCESS';
export const GET_READ_ERROR = 'GET_READ_ERROR';
export const GET_SENT_SUCCESS = 'GET_SENT_SUCCESS';
export const GET_SENT_ERROR = 'GET_SENT_ERROR';
export const GET_DRAFT_SUCCESS = 'GET_DRAFT_SUCCESS';
export const GET_DRAFT_ERROR = 'GET_DRAFT_ERROR';
export const POST_MAIL_SUCCESS = 'POST_MAIL_SUCCESS';
export const POST_MAIL_ERROR = 'POST_MAIL_ERROR';

